# Generated by Django 3.1.1 on 2021-09-26 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='uploads',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
