version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  api:
    container_name: django-rest-api
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  ui:
    container_name: angular-ui
    build: ./frontend
    ports:
      - "4200:80"
  celerybeat:
    container_name: celerybeat
    build: ./backend
    command: celery -A services beat -l INFO
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - ui
      - db
      - redis
  celeryworker:
    container_name: celeryworker
    build: ./backend
    command: celery -A services worker --pool=solo -l info
    volumes:
      - .:/code
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - ui
      - db
      - redis
  redis:
    container_name: redis
    image: redis:alpine
